/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <io.h>//ch

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, yytext_ptr, yyleng + 1 ); \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 129
#define YY_END_OF_BUFFER 130
static yyconst short int yy_acclist[424] =
    {   0,
      130,    3,  129,    4,  129,    3,  129,  128,  129,  127,
      128,  129,  127,  129,  100,  128,  129,    7,  128,  129,
      128,  129,  113,  128,  129,  128,  129,    8,  128,  129,
       87,  128,  129,   88,  128,  129,  109,  128,  129,  105,
      128,  129,   98,  128,  129,  107,  128,  129,   95,  128,
      129,  111,  128,  129,   52,  128,  129,   52,  128,  129,
       96,  128,  129,   99,  128,  129,  122,  128,  129,  126,
      128,  129,  120,  128,  129,  128,  129,   86,  128,  129,
       89,  128,  129,   90,  128,  129,   86,  128,  129,   86,
      128,  129,   86,  128,  129,   86,  128,  129,   86,  128,

      129,   86,  128,  129,   86,  128,  129,   86,  128,  129,
       86,  128,  129,   86,  128,  129,   86,  128,  129,   86,
      128,  129,   86,  128,  129,   86,  128,  129,   86,  128,
      129,   91,  128,  129,  128,  129,   92,  128,  129,   33,
      129,   34,  129,   10,   33,  129,   33,  129,   33,  129,
       33,  129,   11,   33,  129,   33,  129,   33,  129,   33,
      129,16393,   50,  129,   51,  129,   50,  129,   32,  129,
      129,   20,   32,  129,  129,   20,  129,   17,  129,   19,
      129,   28,  129,   26,  129,   24,  129,   25,  129,   29,
      129,   27,  129,   23,  129,   22,  129,   22,  129,   21,

      129,   31,  129,   31,  129,   30,  129,   15,  129,   16,
      129,  127,  118,   85,  114,  102,  110,  115,  106,  116,
      108,   94,   48,   47,  112,   53,   52,   97,  123,  119,
      117,   93,  121,    2,   86,   86,   86,   68,   86,   86,
       86,   86,   86,   69,   86,   86,   86,   86,   86,   86,
       86,   59,   86,   86,   86,  103,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,  101,   12,   37,   43,
       45,   35,   44,   42,   38,   39,   40,   41,   36, 8201,
    16393,16393,   49,   18,   19,   22,   21,   31,   30,  125,
    16389,   85,   47,   54,   55,  124,   86,  104,   86,   86,

       86,   86,   86,   86,   86,   86,   86,   66,   86,   86,
       71,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   75,   86,   86,   12,   14,   45,   46,   13, 8197,
    16389,   86,   86,   63,   86,   86,   86,   83,   86,   60,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   73,   86,   56,   86,   86,   14,   45,
       46,   13,    1,16389,   58,   86,   64,   86,   72,   86,
       86,   86,   86,   57,   86,   86,   86,   86,   84,   86,
       86,   86,   86,   86,   86,   86,   70,   86,16390,   86,
       61,   86,   86,   86,   86,   80,   86,   86,   86,   76,

       86,   82,   86,   79,   86,   62,   86, 8198,   65,   86,
       74,   86,   67,   86,   86,   77,   86,   86,   81,   86,
       86,   78,   86
    } ;

static yyconst short int yy_accept[318] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    4,    6,    8,   10,
       13,   15,   18,   21,   23,   26,   28,   31,   34,   37,
       40,   43,   46,   49,   52,   55,   58,   61,   64,   67,
       70,   73,   76,   78,   81,   84,   87,   90,   93,   96,
       99,  102,  105,  108,  111,  114,  117,  120,  123,  126,
      129,  132,  135,  137,  140,  142,  144,  147,  149,  151,
      153,  156,  158,  160,  163,  165,  167,  169,  171,  172,

      175,  176,  178,  180,  182,  184,  186,  188,  190,  192,
      194,  196,  198,  200,  202,  204,  206,  208,  210,  212,
      212,  213,  214,  214,  215,  216,  217,  218,  219,  220,
      221,  222,  223,  224,  225,  226,  227,  227,  227,  228,
      229,  229,  230,  231,  232,  233,  234,  235,  236,  237,
      238,  240,  241,  242,  243,  244,  246,  247,  248,  249,
      250,  251,  252,  254,  255,  257,  258,  259,  260,  261,
      262,  263,  264,  265,  266,  267,  268,  269,  269,  270,
      271,  272,  273,  274,  275,  276,  277,  278,  279,  279,
      279,  280,  281,  282,  283,  284,  285,  286,  287,  288,

      289,  290,  290,  291,  292,  292,  293,  294,  295,  296,
      296,  297,  299,  300,  301,  302,  303,  304,  305,  306,
      307,  308,  310,  311,  313,  314,  315,  316,  317,  318,
      319,  320,  321,  322,  324,  325,  326,  327,  328,  329,
      330,  330,  331,  331,  332,  333,  334,  336,  337,  338,
      340,  342,  343,  344,  345,  346,  347,  348,  349,  350,
      351,  352,  353,  354,  356,  358,  359,  360,  361,  362,
      363,  364,  364,  365,  367,  369,  371,  372,  373,  374,
      376,  377,  378,  379,  381,  382,  383,  384,  385,  386,
      387,  389,  390,  390,  391,  393,  394,  395,  396,  398,

      399,  400,  402,  404,  406,  408,  409,  411,  413,  415,
      416,  418,  419,  421,  422,  424,  424
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   28,   28,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   30,   29,   29,
       31,   32,   33,    1,   29,    1,   34,   35,   36,   37,

       38,   39,   29,   40,   41,   29,   42,   43,   29,   44,
       45,   46,   29,   47,   48,   49,   50,   51,   52,   53,
       54,   29,   55,   56,   57,    1,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    1,    6,    1,    1,    1,    1,    7,    8,    8,
        1,    1,    1,    7,    7,    7,    7,    7,    7,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    9,    1,    1
    } ;

static yyconst short int yy_base[347] =
    {   0,
        0,    1,   25,    0,   80,   84,   85,   88,   89,  142,
      585,   78,    2,    3,   93,   95,   84,   92,    0,    0,
        0,    0,  170,    0,  140,  218,  234,    0,  271,    0,
      584,  583,  582,  581,  583,  589,  589,  555,  589,    5,
        7,  556,    0,    0,  555,  571,  589,  589,  589,  553,
       80,  589,   88,  589,   94,  208,    0,  555,  589,   76,
       83,  551,  549,    0,  589,  589,   81,  527,   84,   92,
      107,  117,  534,  534,  524,  195,  532,   82,  114,  535,
      528,  589,  511,  589,  589,  589,  589,  511,  321,  559,
      589,  127,  559,  119,  589,  589,  546,  589,  589,  589,

      536,  589,  589,    0,  589,  589,  589,  589,  589,  589,
      589,  589,  145,    0,  589,  228,    0,  589,  589,  515,
        9,  535,  554,    0,  589,  589,  589,  589,  589,  589,
      589,  589,  589,    0,  589,  183,    0,    4,  238,  589,
      534,  589,  589,  532,  589,  589,  589,    0,  519,  508,
        0,  516,  505,  518,  512,    0,  510,  501,  499,  504,
      499,  501,    0,  492,    0,  496,  191,  507,  492,  506,
      498,  497,  487,  489,  494,  589,    0,    0,  589,  589,
      221,  589,  589,  589,  589,  589,  589,  589,    0,    0,
      589,  589,  135,  531,  589,  589,    0,  275,    0,  310,

        0,  493,  589,  529,  526,    0,    0,    0,  150,  519,
      589,    0,  489,  487,  482,  466,  477,  462,  465,  464,
      449,  453,  452,    0,  441,  193,  426,  428,  419,  416,
      412,  409,  413,    0,  407,    0,    0,  247,    0,    0,
      397,  589,    0,  370,  317,  327,    0,  319,  316,    0,
      323,  319,  324,  327,  309,  313,  307,  321,  316,  311,
      304,  309,  313,    0,    0,  310,    0,  589,  589,    0,
      589,  338,  343,    0,    0,    0,  302,  305,  306,    0,
      306,  297,  288,    0,  287,  299,  298,  289,  296,  264,
        0,  300,  293,  249,    0,  249,  220,  205,    0,  137,

       97,    0,    0,    0,    0,  589,    0,    0,    0,   96,
        0,   94,    0,   67,    0,  589,  374,  383,  392,  401,
      410,  419,  428,  431,  433,  437,  439,  447,  451,  455,
      459,  465,  469,  477,  482,  485,  487,  491,  492,  497,
      501,  505,  508,  510,  517,  522
    } ;

static yyconst short int yy_def[347] =
    {   0,
      317,  317,  316,    3,  318,  318,  318,  318,  318,  318,
      318,   10,  319,  319,  320,  320,  321,  321,  321,  321,
      321,  321,  321,   23,  321,  321,  321,   27,   27,   29,
      322,  322,  323,  323,  316,  316,  316,  316,  316,  316,
      316,  316,  324,  325,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  326,  316,  316,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  316,  316,  316,  316,  316,  316,  327,  316,  316,
      316,  316,   89,  328,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  329,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  330,  316,  316,  331,  316,  316,  316,
      316,  316,  332,  333,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  334,  316,  316,  335,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  316,  336,  337,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  338,  339,
      316,  316,  328,  316,  316,  316,  329,  316,  330,  316,

      331,  316,  316,  316,  332,  333,  334,  335,  316,  340,
      316,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  336,  341,  316,  342,  343,
      316,  316,  344,  345,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  341,  316,  316,  343,
      316,  346,  345,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  316,  346,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  316,  326,  326,  326,  326,
      326,  326,  326,  326,  326,    0,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316
    } ;

static yyconst short int yy_nxt[647] =
    {   0,
      316,  316,   37,   37,   96,   96,  121,  121,  121,  121,
      121,  121,  316,   97,   97,  316,  316,  139,  139,  139,
      139,  209,  209,   38,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   57,   57,   58,   59,   60,   61,
       62,   63,   64,   64,   64,   65,   39,   66,   67,   68,
       69,   70,   71,   72,   64,   73,   64,   64,   74,   75,
       76,   77,   78,   79,   64,   80,   81,   64,   64,   82,
       83,   84,   86,   85,   87,   88,   86,   86,   87,   88,
       86,   86,  128,   91,   88,   99,   91,   99,  101,  141,

      142,  143,  130,  315,  129,  133,  101,  144,  145,   85,
      134,   89,  131,  132,  102,   89,   92,  153,  135,   92,
       93,  192,  102,  100,  149,  100,  154,  150,  151,  155,
      170,  314,   85,  171,   90,  191,  156,  192,   90,  313,
      103,  194,  157,   90,   86,  312,  105,   88,  103,  158,
      160,  106,  107,  172,  108,  109,  110,  194,  182,  159,
      173,  161,  198,  198,  198,  198,  162,  209,  209,   94,
       94,   94,  111,   93,  311,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   90,  104,  104,  104,

      136,  136,  136,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  105,  136,  136,  136,  166,  106,
      107,  226,  108,  109,  110,  227,  257,  137,  238,  238,
      238,  167,  138,  258,  168,  200,  200,  200,  200,  310,
      111,  112,  113,  113,  113,  139,  139,  139,  139,  309,
      137,  114,  114,  114,  268,  268,  268,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  115,  116,
      116,  116,  198,  198,  198,  198,  308,  307,  117,  117,

      117,  292,  306,  305,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  179,  180,  200,  200,  200,
      200,  304,  303,  302,  301,  300,  299,  298,  181,  181,
      181,  297,  296,  295,  294,  242,  292,  291,  290,  289,
      288,  287,  182,  286,  285,  284,  283,  282,  183,  184,
      281,  280,  279,  278,  185,  277,  276,  186,  275,  187,
      274,  188,  242,  189,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       99,   99,   99,   99,   99,   99,   99,   99,   99,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  123,  123,  124,
      124,  148,  271,  148,  148,  177,  177,  177,  193,  266,
      265,  193,  193,  193,  193,  197,  264,  197,  197,  199,
      263,  199,  199,  201,  262,  201,  201,  205,  261,  205,
      260,  205,  205,  206,  259,  206,  206,  207,  256,  207,
      207,  207,  207,  207,  207,  207,  208,  255,  208,  236,
      254,  236,  236,  237,  237,  239,  253,  239,  240,  240,

      244,  252,  251,  244,  244,  267,  250,  267,  267,  269,
      249,  269,  270,  248,  270,  270,  272,  272,  273,  247,
      246,  273,  245,  273,  273,  293,  293,  243,  293,  293,
      204,  242,  241,  192,  235,  234,  233,  232,  231,  230,
      229,  228,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  204,  203,
      202,  196,  195,  316,  190,  178,  176,  175,  174,  169,
      165,  164,  163,  152,  147,  146,  140,  127,  126,  125,
      122,  120,  316,   99,   99,   99,   99,   86,   35,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316
    } ;

static yyconst short int yy_chk[647] =
    {   0,
        0,    0,    1,    2,   13,   14,   40,   40,   41,   41,
      121,  121,    0,   13,   14,    0,    0,   57,   57,   57,
       57,  138,  138,    1,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    5,   12,    5,    5,    6,    7,    6,    6,
        8,    9,   51,    7,    9,   15,    8,   16,   17,   60,

       60,   60,   53,  314,   51,   55,   18,   61,   61,   12,
       55,    5,   53,   53,   17,    6,    7,   69,   55,    8,
        9,   94,   18,   15,   67,   16,   69,   67,   67,   70,
       78,  312,   12,   78,    5,   92,   70,  193,    6,  310,
       17,   94,   71,    9,   10,  301,   25,   10,   18,   71,
       72,   25,   25,   79,   25,   25,   25,  193,   92,   71,
       79,   72,  113,  113,  113,  113,   72,  209,  209,   10,
       10,   10,   25,   10,  300,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   23,   23,   23,

      136,  136,  136,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   26,   56,   56,   56,   76,   26,
       26,  167,   26,   26,   26,  167,  226,   56,  181,  181,
      181,   76,   56,  226,   76,  116,  116,  116,  116,  298,
       26,   27,   27,   27,   27,  139,  139,  139,  139,  297,
       56,   27,   27,   27,  238,  238,  238,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   29,   29,
       29,   29,  198,  198,  198,  198,  296,  294,   29,   29,

       29,  293,  292,  290,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   89,   89,  200,  200,  200,
      200,  289,  288,  287,  286,  285,  283,  282,   89,   89,
       89,  281,  279,  278,  277,  273,  272,  266,  263,  262,
      261,  260,   89,  259,  258,  257,  256,  255,   89,   89,
      254,  253,  252,  251,   89,  249,  248,   89,  246,   89,
      245,   89,  244,   89,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  319,  319,  319,  319,  319,  319,  319,  319,

      319,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  324,  324,  325,
      325,  326,  241,  326,  326,  327,  327,  327,  328,  235,
      233,  328,  328,  328,  328,  329,  232,  329,  329,  330,
      231,  330,  330,  331,  230,  331,  331,  332,  229,  332,
      228,  332,  332,  333,  227,  333,  333,  334,  225,  334,
      334,  334,  334,  334,  334,  334,  335,  223,  335,  336,
      222,  336,  336,  337,  337,  338,  221,  338,  339,  339,

      340,  220,  219,  340,  340,  341,  218,  341,  341,  342,
      217,  342,  343,  216,  343,  343,  344,  344,  345,  215,
      214,  345,  213,  345,  345,  346,  346,  210,  346,  346,
      205,  204,  202,  194,  175,  174,  173,  172,  171,  170,
      169,  168,  166,  164,  162,  161,  160,  159,  158,  157,
      155,  154,  153,  152,  150,  149,  144,  141,  123,  122,
      120,  101,   97,   93,   90,   88,   83,   81,   80,   77,
       75,   74,   73,   68,   63,   62,   58,   50,   46,   45,
       42,   38,   35,   34,   33,   32,   31,   11,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "flexInput.txt"
#define INITIAL 0
#line 2 "flexInput.txt"
    #include <conio.h>
    #include <string.h>
	#include "bison_input.yacc_tab.h"
	#define PHP_DEBUG

	int start_condition[64];
	int condition_num = 0;
    char docName[64];
    char lexem[256];
	char html[512] = "";
#ifdef PHP_DEBUG
	char comment[512] = "";
#endif
	void beginCondition();
	void changeStartCondition(int condition);
	void addStartCondition(int condition);
	void returnStartCondition();
	void debugyy(char* msg, char* txt);
	void debug_clear(char* com);
	void debug_strcat(char* com, char* txt);
	void writeIntToUnion(char* num, char* base);
	void writeBinToUnion(char* num);
	void writeCharToUnion(char* const_char);
	void writeIdToUnion(char* id);
	void writeHtmlToUnion(char* uhtml);
	void printLex(char* lexemName, char* txt);
	void getDocName();
	int docNameCheck(char* name, char* txt);
	int strToNumber(char* num, char* base);
	int strToBin(char* num);
	void strcat_code(char* lex, int code);
	void strcat_strcode(char* lex, char* code);
	
	extern union YYSTYPE yylval;
#define YY_NEVER_INTERACTIVE 1
#define PHP 1

#define STR 2

#define STR_SINGLE_QUOTATION 3

#define HEREDOC 4

#define NOWDOC 5

#define COMMENT 6

#define VAR 7

#define COMPLEX_VAR 8

#define VAR_BEGIN 9

#define COMPLEX_VAR_BEGIN 10

#define VAR_ARROW 11

#define VAR_INDEX 12

#define VAR_INDEX_BEGIN 13

#define VAR_INDEX_EXPR 14

#define VAR1 15

#define VAR2 16

#line 763 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 67 "flexInput.txt"


#line 916 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yyleng;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 317 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 589 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 69 "flexInput.txt"
{if (strlen(html) != 0) {writeHtmlToUnion(html);} beginCondition(); addStartCondition(PHP); return HTML;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 70 "flexInput.txt"
{returnStartCondition();}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 72 "flexInput.txt"
strcat(html, yytext);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 73 "flexInput.txt"
strcat(html, yytext);
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 74 "flexInput.txt"
{if (strlen(html) != 0) {writeHtmlToUnion(html);} return HTML;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 76 "flexInput.txt"
{getDocName(); strcpy(lexem, ""); addStartCondition(HEREDOC);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 77 "flexInput.txt"
{getDocName(); strcpy(lexem, ""); addStartCondition(NOWDOC);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 78 "flexInput.txt"
{strcpy(lexem, ""); addStartCondition(STR);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 79 "flexInput.txt"
{strcpy(lexem, ""); addStartCondition(STR_SINGLE_QUOTATION);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "flexInput.txt"
{if (docNameCheck(docName, yytext)) {writeCharToUnion(lexem); returnStartCondition(); return CHAR_CONST;} else strcat(lexem, yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "flexInput.txt"
{writeCharToUnion(lexem); returnStartCondition(); return CHAR_CONST;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "flexInput.txt"
{writeCharToUnion(lexem); returnStartCondition(); return CHAR_CONST;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 85 "flexInput.txt"
{writeCharToUnion(lexem); strcpy(lexem, yytext+1); unput('1'); addStartCondition(VAR1); return CHAR_CONST;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 86 "flexInput.txt"
{writeCharToUnion(lexem); strcpy(lexem, yytext+2); unput('2'); addStartCondition(VAR1); return CHAR_CONST;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 87 "flexInput.txt"
{writeCharToUnion(lexem); strcpy(lexem, yytext+2); unput('2'); addStartCondition(VAR1); return CHAR_CONST;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 88 "flexInput.txt"
{unput(yytext[0]); changeStartCondition(VAR2); return '.';}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 89 "flexInput.txt"
{writeIdToUnion(lexem); if (yytext[0] == '1') changeStartCondition(VAR_BEGIN); else changeStartCondition(COMPLEX_VAR_BEGIN); return VARNAME;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 90 "flexInput.txt"
{returnStartCondition();}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 92 "flexInput.txt"
{addStartCondition(VAR_ARROW); return ARROW;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 93 "flexInput.txt"
{writeIdToUnion(yytext); returnStartCondition(); return ID;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 95 "flexInput.txt"
{addStartCondition(VAR_INDEX_BEGIN); return '[';}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 96 "flexInput.txt"
{writeIdToUnion(yytext); changeStartCondition(VAR_INDEX); return ID;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 97 "flexInput.txt"
{writeIntToUnion(yytext, "%d"); changeStartCondition(VAR_INDEX); return INT_CONST;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 98 "flexInput.txt"
{returnStartCondition(); return ']';}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "flexInput.txt"
{addStartCondition(VAR_INDEX_EXPR); return '+';}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 100 "flexInput.txt"
{addStartCondition(VAR_INDEX_EXPR); return '-';}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "flexInput.txt"
{addStartCondition(VAR_INDEX_EXPR); return '*';}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 102 "flexInput.txt"
{addStartCondition(VAR_INDEX_EXPR); return '/';}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 103 "flexInput.txt"
{addStartCondition(VAR_INDEX_EXPR); return '%';}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 104 "flexInput.txt"
{addStartCondition(VAR_INDEX_EXPR); return '.';}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 105 "flexInput.txt"
{writeIdToUnion(yytext); returnStartCondition(); return ID;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 106 "flexInput.txt"
{writeIntToUnion(yytext, "%d"); returnStartCondition(); return INT_CONST;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 108 "flexInput.txt"
{unput(yytext[0]); returnStartCondition();}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 110 "flexInput.txt"
strcat(lexem, yytext);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 111 "flexInput.txt"
strcat(lexem, yytext);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 112 "flexInput.txt"
strcat(lexem, "\\");
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 113 "flexInput.txt"
strcat(lexem, "'");
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 114 "flexInput.txt"
strcat(lexem, "\"");
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 115 "flexInput.txt"
strcat(lexem, "\n");
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 116 "flexInput.txt"
strcat(lexem, "\r");
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 117 "flexInput.txt"
strcat(lexem, "\t");
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 118 "flexInput.txt"
strcat(lexem, "\v");
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 119 "flexInput.txt"
strcat(lexem, "\f");
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 120 "flexInput.txt"
strcat(lexem, "$");
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 121 "flexInput.txt"
strcat_code(lexem, 27);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 122 "flexInput.txt"
strcat_strcode(lexem, yytext);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 123 "flexInput.txt"
strcat_strcode(lexem, yytext);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 125 "flexInput.txt"

	YY_BREAK
case 48:
YY_RULE_SETUP
#line 127 "flexInput.txt"
{BEGIN(COMMENT);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 128 "flexInput.txt"
{BEGIN(PHP);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 129 "flexInput.txt"

	YY_BREAK
case 51:
YY_RULE_SETUP
#line 130 "flexInput.txt"

	YY_BREAK
case 52:
YY_RULE_SETUP
#line 132 "flexInput.txt"
{writeIntToUnion(yytext, "%d"); return INT_CONST;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 133 "flexInput.txt"
{writeIntToUnion(yytext, "%o"); return INT_CONST;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 134 "flexInput.txt"
{writeIntToUnion(yytext, "%x"); return INT_CONST;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 135 "flexInput.txt"
{writeBinToUnion(yytext); return INT_CONST;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 137 "flexInput.txt"
{yylval.intConstUnionType = 1; return BOOL_CONST;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 138 "flexInput.txt"
{yylval.intConstUnionType = 0; return BOOL_CONST;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 140 "flexInput.txt"
{return ARRAY;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 142 "flexInput.txt"
{return IF;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 143 "flexInput.txt"
{return ELSE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 144 "flexInput.txt"
{return ELSEIF;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 145 "flexInput.txt"
{return SWITCH;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 146 "flexInput.txt"
{return CASE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 147 "flexInput.txt"
{return BREAK;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 148 "flexInput.txt"
{return DEFAULT;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 150 "flexInput.txt"
{return FOR;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 151 "flexInput.txt"
{return FOREACH;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 152 "flexInput.txt"
{return AS;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 153 "flexInput.txt"
{return DO;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 154 "flexInput.txt"
{return WHILE;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 156 "flexInput.txt"
{return NEW;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 157 "flexInput.txt"
{return CLASS;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 158 "flexInput.txt"
{return THIS;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 159 "flexInput.txt"
{return EXTENDS;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 160 "flexInput.txt"
{return PUBLIC;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 161 "flexInput.txt"
{return PUBLIC;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 162 "flexInput.txt"
{return PRIVATE;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 163 "flexInput.txt"
{return PROTECTED;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 164 "flexInput.txt"
{return STATIC;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 165 "flexInput.txt"
{return PARENT;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 167 "flexInput.txt"
{return FUNCTION;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 168 "flexInput.txt"
{return RETURN;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 170 "flexInput.txt"
{return ECHO;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 171 "flexInput.txt"
{return ECHO;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 173 "flexInput.txt"
{writeIdToUnion(yytext); return VARNAME;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 174 "flexInput.txt"
{writeIdToUnion(yytext); return ID;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 176 "flexInput.txt"
{return (unsigned char)'(';}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 177 "flexInput.txt"
{return (unsigned char)')';}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 178 "flexInput.txt"
{return (unsigned char)'[';}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 179 "flexInput.txt"
{return (unsigned char)']';}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 180 "flexInput.txt"
{return (unsigned char)'{';}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 181 "flexInput.txt"
{return (unsigned char)'}';}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 183 "flexInput.txt"
{return SETVALUE;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 184 "flexInput.txt"
{return ARROW;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 185 "flexInput.txt"
{return (unsigned char)'.';}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 186 "flexInput.txt"
{return (unsigned char)':';}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 187 "flexInput.txt"
{return SCOPEOP;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 189 "flexInput.txt"
{return (unsigned char)',';}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 190 "flexInput.txt"
{return (unsigned char)';';}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 192 "flexInput.txt"
{return (unsigned char)'!';}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 193 "flexInput.txt"
{return COR;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 194 "flexInput.txt"
{return CAND;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 195 "flexInput.txt"
{return POR;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 196 "flexInput.txt"
{return PAND;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 198 "flexInput.txt"
{return (unsigned char)'+';}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 199 "flexInput.txt"
{return PLUSAS;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 200 "flexInput.txt"
{return (unsigned char)'-';}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 201 "flexInput.txt"
{return MINUSAS;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 202 "flexInput.txt"
{return (unsigned char)'*';}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 203 "flexInput.txt"
{return MULTAS;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 204 "flexInput.txt"
{return (unsigned char)'/';}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 205 "flexInput.txt"
{return DIVAS;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 206 "flexInput.txt"
{return (unsigned char)'%';}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 207 "flexInput.txt"
{return MODAS;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 208 "flexInput.txt"
{return INC;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 209 "flexInput.txt"
{return DEC;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 211 "flexInput.txt"
{return EQ;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 212 "flexInput.txt"
{return NEQ;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 213 "flexInput.txt"
{return NEQ;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 214 "flexInput.txt"
{return (unsigned char)'>';}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 215 "flexInput.txt"
{return GEQ;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 216 "flexInput.txt"
{return (unsigned char)'<';}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 217 "flexInput.txt"
{return LEQ;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 218 "flexInput.txt"
{return TEQ;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 219 "flexInput.txt"
{return TNEQ;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 221 "flexInput.txt"
{return (unsigned char)'=';}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 223 "flexInput.txt"
;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 224 "flexInput.txt"
printf("character_not_found");
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 226 "flexInput.txt"
ECHO;
	YY_BREAK
#line 1686 "lex.yy.c"
			case YY_STATE_EOF(PHP):
			case YY_STATE_EOF(STR):
			case YY_STATE_EOF(STR_SINGLE_QUOTATION):
			case YY_STATE_EOF(HEREDOC):
			case YY_STATE_EOF(NOWDOC):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(VAR):
			case YY_STATE_EOF(COMPLEX_VAR):
			case YY_STATE_EOF(VAR_BEGIN):
			case YY_STATE_EOF(COMPLEX_VAR_BEGIN):
			case YY_STATE_EOF(VAR_ARROW):
			case YY_STATE_EOF(VAR_INDEX):
			case YY_STATE_EOF(VAR_INDEX_BEGIN):
			case YY_STATE_EOF(VAR_INDEX_EXPR):
			case YY_STATE_EOF(VAR1):
			case YY_STATE_EOF(VAR2):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 317 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 317 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 316);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 226 "flexInput.txt"


void beginCondition()
{
	start_condition[0] = INITIAL;
}

void addStartCondition(int condition)
{
	condition_num++;
	changeStartCondition(condition);
}

void changeStartCondition(int condition)
{
	start_condition[condition_num] = condition;
	BEGIN(condition);
}

void returnStartCondition()
{
	condition_num--;
	BEGIN(start_condition[condition_num]);
}

void debugyy(char* msg, char* txt)
{
#ifdef PHP_DEBUG
	if (msg != 0)
		printf("DEBUG: %s: [%s]\n", msg, txt);
	else
		printf("%s\n", txt);
#endif
}

void debug_clear(char* com)
{
#ifdef PHP_DEBUG
	strcpy(com, "");
#endif
}

void debug_strcat(char* com, char* txt)
{
#ifdef PHP_DEBUG
	strcat(com, txt);
#endif
}

void writeIntToUnion(char* num, char* base)
{
	yylval.intConstUnionType = strToNumber(num, base);
}

void writeBinToUnion(char* num)
{
	yylval.intConstUnionType = strToBin(num);
}

void writeCharToUnion(char* const_char)
{
	yylval.charConstUnionType = (char*)malloc(sizeof(char)*256);
	strcpy(yylval.charConstUnionType, const_char);
}

void writeIdToUnion(char* id)
{
	yylval.idUnionType = (char*)malloc(sizeof(char)*100);
	strcpy(yylval.idUnionType, id);
}

void writeHtmlToUnion(char* uhtml)
{
	yylval.htmlUnionType = (char*)malloc(sizeof(char)*512);
	strcpy(yylval.htmlUnionType, uhtml);
	strcpy(uhtml, "");
}

void printLex(char* lexemName, char* txt)
{
	printf("%s found: [%s]\n", lexemName, txt);
}

void getDocName()
{
	if ((yytext[3] == '\"') || (yytext[3] == '\''))
	{
		strcpy(docName, yytext+4);
		docName[strlen(docName)-1] = 0;
	}
	else
		strcpy(docName, yytext+3);
}

int docNameCheck(char* name, char* txt)
{
	char dName[65];
	strcpy(dName, name);
	if(!strcmp(dName, txt) || !strcmp(strcat(dName, ";"), txt))
		return 1;
	else
		return 0;
}

int strToNumber(char* num, char* base)
{
	int number;
	sscanf(num, base, &number);
	return number;
}

int strToBin(char* num)
{
	int number = 0;
	int digit = 1;
	int i;
	for (i = strlen(num)-1; i > 1; i--)
	{
		number += (num[i]-48)*digit;
		digit *= 2;
	}
	return number;
}

void strcat_code(char* lex, int code)
{
	char h[2] = {(code%256), 0};
	strcat(lex, h);
}

void strcat_strcode(char* lex, char* code)
{
	int num;
	char copy[5];
	strcpy(copy, code);
	copy[0] = '0';
	if (copy[1] == 'x')
		sscanf(copy, "%x", &num);
	else
		sscanf(copy, "%o", &num);
	strcat_code(lex, num);
}