/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include "unistd.h"

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, yytext_ptr, yyleng + 1 ); \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 106
#define YY_END_OF_BUFFER 107
static yyconst short int yy_acclist[366] =
    {   0,
      107,    3,  106,    4,  106,    3,  106,  105,  106,  104,
      105,  106,  104,  106,   77,  105,  106,    7,  105,  106,
      105,  106,   90,  105,  106,  105,  106,    8,  105,  106,
       64,  105,  106,   65,  105,  106,   86,  105,  106,   82,
      105,  106,   75,  105,  106,   84,  105,  106,   72,  105,
      106,   88,  105,  106,   32,  105,  106,   32,  105,  106,
       73,  105,  106,   76,  105,  106,   99,  105,  106,  103,
      105,  106,   97,  105,  106,  105,  106,   63,  105,  106,
       66,  105,  106,   67,  105,  106,   63,  105,  106,   63,
      105,  106,   63,  105,  106,   63,  105,  106,   63,  105,

      106,   63,  105,  106,   63,  105,  106,   63,  105,  106,
       63,  105,  106,   63,  105,  106,   63,  105,  106,   63,
      105,  106,   63,  105,  106,   63,  105,  106,   63,  105,
      106,   68,  105,  106,  105,  106,   69,  105,  106,   12,
      106,   13,  106,   10,   12,  106,   12,  106,   12,  106,
       12,  106,   11,   12,  106,   12,  106,   12,  106,   12,
      106,16393,   29,  106,   30,  106,   29,  106,  104,   95,
       62,   91,   79,   87,   92,   83,   93,   85,   71,   28,
       27,   89,   33,   32,   74,  100,   96,   94,   70,   98,
        2,   63,   63,   63,   47,   63,   63,   63,   63,   63,

       48,   63,   63,   63,   63,   63,   63,   38,   63,   63,
       63,   80,   63,   63,   63,   63,   63,   63,   63,   63,
       78,   26,   16,   22,   24,   14,   23,   21,   17,   18,
       19,   20,   15, 8201,16393,16393,   31,  102,16389,   62,
       27,   34,   35,  101,   63,   81,   63,   63,   63,   63,
       63,   63,   63,   63,   45,   63,   63,   50,   63,   63,
       63,   63,   63,   63,   63,   63,   36,   63,   63,   26,
       24,   25, 8197,16389,   63,   63,   42,   63,   63,   63,
       60,   63,   39,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   52,   63,   63,   62,   24,   25,

       26,    1,   62,   62,16389,   37,   63,   43,   63,   51,
       63,   63,   63,   63,   63,   63,   61,   63,   63,   63,
       63,   63,   63,   63,   49,   63,   26,   26,   62,16390,
       63,   40,   63,   63,   63,   63,   63,   63,   54,   63,
       59,   63,   57,   63,   41,   63,   26, 8198,   44,   63,
       53,   63,   46,   63,   63,   55,   63,   63,   62,   58,
       63,   63,   26,   56,   63
    } ;

static yyconst short int yy_accept[318] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    4,    6,    8,   10,
       13,   15,   18,   21,   23,   26,   28,   31,   34,   37,
       40,   43,   46,   49,   52,   55,   58,   61,   64,   67,
       70,   73,   76,   78,   81,   84,   87,   90,   93,   96,
       99,  102,  105,  108,  111,  114,  117,  120,  123,  126,
      129,  132,  135,  137,  140,  142,  144,  147,  149,  151,
      153,  156,  158,  160,  163,  165,  167,  169,  169,  170,
      171,  171,  171,  172,  173,  174,  175,  176,  177,  178,
      179,  180,  181,  182,  183,  184,  184,  184,  185,  186,

      186,  187,  188,  189,  190,  191,  192,  193,  194,  195,
      197,  198,  199,  200,  201,  203,  204,  205,  206,  207,
      208,  210,  211,  213,  214,  215,  216,  217,  218,  219,
      220,  221,  221,  222,  222,  223,  224,  225,  226,  227,
      228,  229,  230,  231,  232,  233,  233,  233,  234,  235,
      236,  237,  238,  238,  239,  240,  240,  240,  241,  241,
      242,  243,  244,  244,  245,  247,  248,  249,  250,  251,
      252,  253,  254,  255,  257,  258,  260,  261,  262,  263,
      264,  265,  266,  267,  269,  270,  270,  270,  271,  271,
      272,  273,  273,  273,  274,  274,  274,  274,  274,  275,

      276,  277,  279,  280,  281,  283,  285,  286,  287,  288,
      289,  290,  291,  292,  293,  294,  295,  297,  298,  298,
      298,  298,  299,  299,  299,  299,  300,  301,  301,  301,
      301,  302,  303,  304,  305,  305,  305,  306,  308,  310,
      312,  313,  314,  315,  316,  317,  319,  320,  321,  322,
      323,  324,  325,  327,  327,  327,  327,  328,  329,  329,
      329,  329,  329,  330,  330,  331,  331,  332,  334,  335,
      336,  337,  338,  339,  341,  343,  345,  347,  347,  347,
      347,  348,  348,  348,  348,  348,  348,  348,  349,  351,
      353,  355,  356,  358,  359,  359,  359,  359,  359,  359,

      359,  360,  360,  362,  363,  363,  363,  364,  364,  364,
      364,  366,  366,  366,  366,  366,  366
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   28,   28,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   30,   29,   29,
       31,   32,   33,    1,   29,    1,   34,   35,   36,   37,

       38,   39,   29,   40,   41,   29,   42,   43,   29,   44,
       45,   46,   29,   47,   48,   49,   50,   51,   52,   53,
       54,   29,   55,   56,   57,    1,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    3,    4,    1,    1,    5,    1,
        1,    1,    1,    1,    6,    1,    1,    7,    7,    7,
        7,    1,    8,    1,    1,    1,    1,    9,   10,   10,
        6,    1,    1,    9,    9,    9,    9,    9,    9,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,    1,    1,   11
    } ;

static yyconst short int yy_base[348] =
    {   0,
        0,    1,   25,    0,   80,   84,   85,   88,   89,  142,
      632,   78,    2,    3,  634,  636,  636,  606,  636,    5,
        7,  607,    0,  625,  605,  621,  636,  636,  636,  603,
       80,  636,   81,  636,   86,  106,    0,  605,  636,   75,
       83,  601,  599,    0,  636,  636,   71,  577,   70,   84,
       87,   82,  584,  584,  574,   81,  582,   85,  579,  584,
      577,  610,  559,  636,  636,  636,  636,  608,  193,  607,
      636,  129,  607,  139,  636,  636,  594,  564,    9,  584,
      603,  601,  132,  636,  636,  636,  636,  636,  636,  636,
      636,  636,    0,  636,  131,    0,    4,  134,  636,  582,

      636,  636,  580,  636,  636,  636,    0,  567,  556,    0,
      564,  553,  566,  560,    0,  555,  541,  533,  528,  529,
        0,  517,    0,  115,  527,  511,  525,  517,  516,  501,
      503,    0,  636,  533,  142,  636,  636,  146,  636,  636,
      636,  636,  636,  636,  636,    0,    0,  636,  636,  197,
      531,  636,  493,  636,  529,  522,  497,  186,  184,    0,
        0,  149,  508,  636,    0,  472,  468,  459,  447,  460,
      448,  449,  448,  447,  448,    0,  163,  431,  436,  428,
      428,  424,  421,    0,  425,  191,  441,  193,  208,  215,
        0,  208,  420,  636,    0,  395,  231,    0,  424,  372,

      383,    0,  376,  373,    0,  381,  377,  386,  370,  369,
      378,  373,  369,  359,  363,  367,    0,  364,  362,  223,
      237,  636,    0,  354,  241,  636,  636,  360,  232,  248,
      636,  636,  255,  256,  257,  374,  376,    0,    0,    0,
      335,  329,  310,  310,  304,    0,  294,  286,  237,  209,
      209,  203,    0,    0,  208,  263,  257,  264,  273,    0,
      203,  279,  270,  284,  227,  212,  170,    0,  170,  176,
      170,  172,  160,    0,    0,    0,    0,  292,  293,  295,
      294,  299,  295,  296,  311,  142,  315,  636,    0,    0,
        0,  125,    0,  120,  306,  320,  113,  336,  327,  341,

      336,  352,    0,  106,   81,  356,  349,  372,   69,  376,
        0,  350,  380,  351,  396,  636,  429,  440,  451,  454,
      461,  465,  472,  481,  489,  494,  504,  509,  510,  515,
      519,  520,  526,  531,  536,  540,  543,  545,  554,  556,
      561,  567,  569,  574,  576,  581,  587
    } ;

static yyconst short int yy_def[348] =
    {   0,
      317,  317,  316,    3,  318,  318,  318,  318,  318,  318,
      318,   10,  319,  319,  316,  316,  316,  316,  316,  316,
      316,  316,  320,  321,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  322,  316,  316,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  316,  316,  316,  316,  316,  316,  323,  316,  316,
      316,  316,   69,  324,  316,  316,  316,  316,  316,  316,
      325,  321,  326,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  327,  316,  316,  328,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  329,  316,  323,  330,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  331,  332,  316,  316,  324,
      316,  316,  316,  316,  316,  325,  316,  326,  316,  327,
      328,  316,  333,  316,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  334,  316,  330,  316,  316,
      335,  336,  316,  316,  337,  316,  316,  338,  339,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  316,  334,
      316,  316,  340,  316,  316,  316,  316,  316,  336,  316,
      316,  316,  341,  316,  316,  342,  339,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  343,  316,  316,  344,  316,  316,  345,
      316,  316,  341,  316,  316,  342,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  346,  316,  316,
      344,  316,  347,  316,  316,  316,  316,  316,  322,  322,
      322,  322,  322,  322,  346,  316,  316,  316,  347,  316,

      316,  316,  322,  322,  316,  316,  316,  316,  316,  316,
      322,  316,  316,  316,  316,    0,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316
    } ;

static yyconst short int yy_nxt[694] =
    {   0,
      316,  316,   17,   17,   76,   76,   79,   79,   79,   79,
       79,   79,  316,   77,   77,  316,  316,   98,   98,   98,
       98,  162,  162,   18,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   37,   37,   38,   39,   40,   41,
       42,   43,   44,   44,   44,   45,   19,   46,   47,   48,
       49,   50,   51,   52,   44,   53,   44,   44,   54,   55,
       56,   57,   58,   59,   44,   60,   61,   44,   44,   62,
       63,   64,   66,   65,   67,   68,   66,   66,   67,   68,
       66,   66,   87,   71,   68,   89,   71,   92,  100,  101,

      102,  314,   93,  112,   88,   90,   91,  103,  104,   65,
       94,   69,  113,  312,  108,   69,   72,  109,  110,   72,
       73,  114,  116,   95,   95,   95,  119,  124,  115,  117,
      125,  120,   65,  127,   70,   96,  128,  148,   70,  118,
       97,  149,  311,   70,   66,  307,  157,   68,   95,   95,
       95,   98,   98,   98,   98,  177,  187,  304,   96,  178,
      139,  151,  159,  190,  190,  190,  162,  162,  303,   74,
       74,   74,  189,   73,  301,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   70,  136,  137,  149,

      157,  196,  197,  197,  197,  219,  210,  187,  294,  293,
      138,  138,  138,  211,  292,  291,  159,  290,  289,  151,
      265,  221,  228,  189,  139,  224,  225,  225,  225,  288,
      140,  141,  226,  226,  226,  284,  142,  219,  230,  143,
      279,  144,  277,  145,  276,  146,  228,  222,  235,  235,
      235,  235,  275,  221,  255,  256,  256,  256,  259,  259,
      259,  259,  230,  234,  231,  261,  262,  262,  262,  157,
      157,  187,  274,  258,  235,  235,  235,  235,  187,  222,
      280,  280,  280,  280,  157,  264,  159,  282,  231,  234,
      259,  259,  259,  259,  189,  279,  285,  285,  285,  285,

      264,  286,  287,  287,  287,  258,  219,  219,  187,  228,
      228,  284,  280,  280,  280,  280,  297,  298,  298,  298,
      219,  273,  296,  221,  282,  300,  230,  279,  285,  285,
      285,  285,  302,  302,  302,  302,  296,  305,  306,  306,
      306,  228,  272,  284,  271,  270,  269,  301,  222,  222,
      157,  231,  231,  308,  308,  308,  308,  300,  309,  310,
      310,  310,  222,  187,  219,  228,  264,  268,  307,  302,
      302,  302,  302,  313,  313,  313,  313,  267,  194,  282,
      296,  300,  265,  231,  301,  260,  258,  254,  312,  308,
      308,  308,  308,  315,  315,  315,  315,  313,  313,  313,

      313,  253,  252,  251,  307,  250,  222,  231,  314,  249,
      248,  247,  312,  315,  315,  315,  315,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  194,  234,  314,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   81,   81,   83,  232,  223,  218,  217,   83,
       83,  107,  216,  107,  107,  135,  215,  214,  213,  212,
      135,  135,  150,  209,  208,  207,  206,  150,  150,  150,
      150,  156,  205,  204,  203,  156,  202,  156,  156,  158,

      158,  201,  158,  158,  160,  200,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  161,  198,  161,  186,  186,
      188,  188,  195,  188,  188,  191,  155,  191,  192,  192,
      199,  194,  193,  149,  199,  199,  220,  220,  316,  220,
      220,  220,  227,  185,  227,  229,  229,  184,  229,  229,
      229,  233,  233,  236,  236,  237,  183,  182,  181,  180,
      237,  179,  237,  237,  257,  257,  263,  263,  176,  263,
      263,  266,  175,  266,  174,  266,  266,  278,  278,  281,
      281,  173,  281,  281,  283,  283,  295,  295,  172,  295,
      295,  295,  299,  299,  171,  299,  299,  299,  170,  169,

      168,  167,  166,  165,  164,  163,  316,  155,  154,  153,
      152,  316,  147,  134,  133,  132,  131,  130,  129,  126,
      123,  122,  121,  111,  106,  105,   99,   86,   85,   84,
       82,   80,   78,  316,   66,   15,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316

    } ;

static yyconst short int yy_chk[694] =
    {   0,
        0,    0,    1,    2,   13,   14,   20,   20,   21,   21,
       79,   79,    0,   13,   14,    0,    0,   37,   37,   37,
       37,   97,   97,    1,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    5,   12,    5,    5,    6,    7,    6,    6,
        8,    9,   31,    7,    9,   33,    8,   35,   40,   40,

       40,  309,   35,   49,   31,   33,   33,   41,   41,   12,
       35,    5,   49,  305,   47,    6,    7,   47,   47,    8,
        9,   50,   51,   36,   36,   36,   52,   56,   50,   51,
       56,   52,   12,   58,    5,   36,   58,   72,    6,   51,
       36,   74,  304,    9,   10,  297,   83,   10,   95,   95,
       95,   98,   98,   98,   98,  124,  135,  294,   36,  124,
       72,   74,   83,  138,  138,  138,  162,  162,  292,   10,
       10,   10,  135,   10,  286,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   69,   69,  150,

      158,  159,  159,  159,  159,  186,  177,  188,  273,  272,
       69,   69,   69,  177,  271,  270,  158,  269,  267,  150,
      266,  186,  192,  188,   69,  189,  189,  189,  189,  265,
       69,   69,  190,  190,  190,  261,   69,  220,  192,   69,
      255,   69,  252,   69,  251,   69,  229,  186,  197,  197,
      197,  197,  250,  220,  221,  221,  221,  221,  225,  225,
      225,  225,  229,  197,  192,  230,  230,  230,  230,  233,
      234,  257,  249,  225,  235,  235,  235,  235,  258,  220,
      256,  256,  256,  256,  263,  233,  234,  257,  229,  235,
      259,  259,  259,  259,  258,  256,  262,  262,  262,  262,

      263,  264,  264,  264,  264,  259,  278,  279,  281,  283,
      284,  262,  280,  280,  280,  280,  282,  282,  282,  282,
      295,  248,  278,  279,  281,  283,  284,  280,  285,  285,
      285,  285,  287,  287,  287,  287,  295,  296,  296,  296,
      296,  299,  247,  285,  245,  244,  243,  287,  278,  279,
      301,  283,  284,  298,  298,  298,  298,  299,  300,  300,
      300,  300,  295,  307,  312,  314,  301,  242,  298,  302,
      302,  302,  302,  306,  306,  306,  306,  241,  237,  307,
      312,  314,  236,  299,  302,  228,  224,  219,  306,  308,
      308,  308,  308,  310,  310,  310,  310,  313,  313,  313,

      313,  218,  216,  215,  308,  214,  312,  314,  310,  213,
      212,  211,  313,  315,  315,  315,  315,  210,  209,  208,
      207,  206,  204,  203,  201,  200,  199,  196,  315,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  320,  320,  321,  193,  187,  185,  183,  321,
      321,  322,  182,  322,  322,  323,  181,  180,  179,  178,
      323,  323,  324,  175,  174,  173,  172,  324,  324,  324,
      324,  325,  171,  170,  169,  325,  168,  325,  325,  326,

      326,  167,  326,  326,  327,  166,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  328,  163,  328,  329,  329,
      330,  330,  157,  330,  330,  331,  156,  331,  332,  332,
      333,  155,  153,  151,  333,  333,  334,  334,  134,  334,
      334,  334,  335,  131,  335,  336,  336,  130,  336,  336,
      336,  337,  337,  338,  338,  339,  129,  128,  127,  126,
      339,  125,  339,  339,  340,  340,  341,  341,  122,  341,
      341,  342,  120,  342,  119,  342,  342,  343,  343,  344,
      344,  118,  344,  344,  345,  345,  346,  346,  117,  346,
      346,  346,  347,  347,  116,  347,  347,  347,  114,  113,

      112,  111,  109,  108,  103,  100,   82,   81,   80,   78,
       77,   73,   70,   68,   63,   62,   61,   60,   59,   57,
       55,   54,   53,   48,   43,   42,   38,   30,   26,   25,
       24,   22,   18,   15,   11,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "flexInput.txt"
#define INITIAL 0
#line 2 "flexInput.txt"
    #include <locale.h>
    #include <conio.h>
    #include <string.h>
	#define PHP_DEBUG
#line 8 "flexInput.txt"
    char docName[64];
    char lexem[16384];
	char html[16384] = "";
#ifdef PHP_DEBUG
	char comment[16384] = "";
#endif
	void debugyy(char* msg, char* txt);
	void debug_clear(char* com);
	void debug_strcat(char* com, char* txt);
	void printLex(char* lexemName, char* txt);
	void getDocName();
	void docNameCheck(char* name, char* txt);
	void printNumber(char* num, char* base);
	void printBin(char* num);
	void strcat_code(char* lex, int code);
	void strcat_strcode(char* lex, char* code);
#define YY_NEVER_INTERACTIVE 1
#define PHP 1

#define STR 2

#define STR_SINGLE_QUOTATION 3

#define HEREDOC 4

#define NOWDOC 5

#define COMMENT 6

#line 735 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 47 "flexInput.txt"


#line 888 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yyleng;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 317 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 636 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 49 "flexInput.txt"
{if (strlen(html) != 0) {printLex("HTML", html); strcpy(html, "");} printLex("BEGIN OF PHP", yytext); BEGIN(PHP);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "flexInput.txt"
{printLex("END OF PHP", yytext); BEGIN(INITIAL);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 "flexInput.txt"
strcat(html, yytext);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "flexInput.txt"
strcat(html, yytext);
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 54 "flexInput.txt"
{if (strlen(html) != 0) {printLex("HTML", html); strcpy(html, "");}}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "flexInput.txt"
{getDocName(); strcpy(lexem, ""); printLex("HEREDOC BEGIN", yytext); BEGIN(HEREDOC);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "flexInput.txt"
{getDocName(); strcpy(lexem, ""); printLex("NOWDOC BEGIN", yytext); BEGIN(NOWDOC);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "flexInput.txt"
{strcpy(lexem, ""); printLex("STRING BEGIN", yytext); BEGIN(STR);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 59 "flexInput.txt"
{strcpy(lexem, ""); printLex("STRING IN SINGLE QUOTES BEGIN", yytext); BEGIN(STR_SINGLE_QUOTATION);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "flexInput.txt"
{debugyy("may be end of doc", yytext); docNameCheck(docName, yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "flexInput.txt"
{if (strlen(lexem) != 0) {printf("%s\n", lexem);} printLex("STRING END", yytext); BEGIN(PHP);} 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "flexInput.txt"
{if (strlen(lexem) != 0) {printf("%s\n", lexem);} printLex("STRING IN SINGLE QUOTES END", yytext); BEGIN(PHP);} 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 63 "flexInput.txt"
strcat(lexem, yytext);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 64 "flexInput.txt"
strcat(lexem, yytext);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "flexInput.txt"
strcat(lexem, "\\");
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "flexInput.txt"
strcat(lexem, "'");
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 "flexInput.txt"
strcat(lexem, "\"");
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "flexInput.txt"
strcat(lexem, "\n");
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 "flexInput.txt"
strcat(lexem, "\r");
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 "flexInput.txt"
strcat(lexem, "\t");
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 71 "flexInput.txt"
strcat(lexem, "\v");
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 "flexInput.txt"
strcat(lexem, "\f");
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 "flexInput.txt"
strcat(lexem, "$");
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 "flexInput.txt"
strcat_code(lexem, 27);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "flexInput.txt"
strcat_strcode(lexem, yytext);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 76 "flexInput.txt"
strcat_strcode(lexem, yytext);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 "flexInput.txt"
{printf("%s\n", lexem); strcpy(lexem, ""); printLex("VARIABLE IN TEXT", yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "flexInput.txt"
debugyy("COMMENT STRING", yytext);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "flexInput.txt"
{debugyy("COMMENT BEGIN", yytext); debug_clear(comment); BEGIN(COMMENT);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "flexInput.txt"
debug_strcat(comment, yytext);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "flexInput.txt"
debug_strcat(comment, yytext);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "flexInput.txt"
{debugyy(0, comment); debugyy("COMMENT END", yytext); BEGIN(PHP);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 "flexInput.txt"
printLex("DECIMAL NUMBER", yytext);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 87 "flexInput.txt"
printNumber(yytext, "%o");
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "flexInput.txt"
printNumber(yytext, "%x");
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 "flexInput.txt"
printBin(yytext);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 91 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 94 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 96 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 97 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 98 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 99 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 100 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 102 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 103 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 104 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 105 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 106 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 108 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 109 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 110 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 111 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 112 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 113 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 114 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 115 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 117 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 118 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 120 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 121 "flexInput.txt"
printLex("KEYWORD", yytext);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 123 "flexInput.txt"
printLex("VARIABLE", yytext);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 124 "flexInput.txt"
printLex("ID", yytext);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 126 "flexInput.txt"
printLex("BRACKET", yytext);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 127 "flexInput.txt"
printLex("BRACKET", yytext);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 128 "flexInput.txt"
printLex("BRACKET", yytext);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 129 "flexInput.txt"
printLex("BRACKET", yytext);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 130 "flexInput.txt"
printLex("BRACKET", yytext);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 131 "flexInput.txt"
printLex("BRACKET", yytext);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 133 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 134 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 135 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 136 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 137 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 139 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 140 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 142 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 143 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 144 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 145 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 146 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 148 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 149 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 150 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 151 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 152 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 153 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 154 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 155 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 156 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 157 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 158 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 159 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 161 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 162 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 163 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 164 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 165 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 166 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 167 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 168 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 169 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 171 "flexInput.txt"
printLex("OPERATOR", yytext);
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 173 "flexInput.txt"
;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 174 "flexInput.txt"
printf("character_not_found");
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 176 "flexInput.txt"
ECHO;
	YY_BREAK
#line 1543 "lex.yy.c"
			case YY_STATE_EOF(PHP):
			case YY_STATE_EOF(STR):
			case YY_STATE_EOF(STR_SINGLE_QUOTATION):
			case YY_STATE_EOF(HEREDOC):
			case YY_STATE_EOF(NOWDOC):
			case YY_STATE_EOF(COMMENT):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 317 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 317 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 316);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 176 "flexInput.txt"


void debugyy(char* msg, char* txt)
{
#ifdef PHP_DEBUG
	if (msg != 0)
		printf("DEBUG: %s: [%s]\n", msg, txt);
	else
		printf("%s\n", txt);
#endif
}

void debug_clear(char* com)
{
#ifdef PHP_DEBUG
	strcpy(com, "");
#endif
}

void debug_strcat(char* com, char* txt)
{
#ifdef PHP_DEBUG
	strcat(com, txt);
#endif
}

void printLex(char* lexemName, char* txt)
{
	printf("%s found: [%s]\n", lexemName, txt);
}

void getDocName()
{
	if ((yytext[3] == '\"') || (yytext[3] == '\''))
	{
		strcpy(docName, yytext+4);
		docName[strlen(docName)-1] = 0;
	}
	else
		strcpy(docName, yytext+3);
}

void docNameCheck(char* name, char* txt)
{
	char dName[65];
	strcpy(dName, name);
	if(!strcmp(dName, txt) || !strcmp(strcat(dName, ";"), txt))
	{
		if (strlen(lexem) != 0)
			printf("%s\n", lexem);
		printLex("DOC END", txt);
		BEGIN(PHP);
	}
	else
	{
		strcat(lexem, yytext);
		debugyy("not end of doc - other id", yytext);
	}
}

void printNumber(char* num, char* base)
{
	int number;
	char format[45];
	if (base[1] == 'o')
		strcpy(format, "OCTAL");
	else
		strcpy(format, "HEXADECIMAL");
	strcat(format, " NUMBER found: [%s] (decimal %d)\n");
	sscanf(num, base, &number);
	printf(format, num, number);
}

void printBin(char* num)
{
	int number = 0;
	int digit = 1;
	int i;
	for (i = strlen(num)-1; i > 1; i--)
	{
		number += (num[i]-48)*digit;
		digit *= 2;
	}
	printf("BINARY NUMBER found: [%s] (decimal %d)\n", num, number);
}

void strcat_code(char* lex, int code)
{
	char h[2] = {(code%256), 0};
	strcat(lex, h);
}

void strcat_strcode(char* lex, char* code)
{
	int num;
	char copy[5];
	strcpy(copy, code);
	copy[0] = '0';
	if (copy[1] == 'x')
		sscanf(copy, "%x", &num);
	else
		sscanf(copy, "%o", &num);
	strcat_code(lex, num);
}