#line 2 "lexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <io.h>    

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, yytext_ptr, yyleng + 1 ); \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
static yyconst short int yy_acclist[372] =
    {   0,
      111,    3,  110,    4,  110,    3,  110,  109,  110,  108,
      109,  110,  108,  110,   81,  109,  110,    7,  109,  110,
      109,  110,   94,  109,  110,  109,  110,    8,  109,  110,
       68,  109,  110,   69,  109,  110,   90,  109,  110,   86,
      109,  110,   79,  109,  110,   88,  109,  110,   76,  109,
      110,   92,  109,  110,   33,  109,  110,   33,  109,  110,
       77,  109,  110,   80,  109,  110,  103,  109,  110,  107,
      109,  110,  101,  109,  110,  109,  110,   67,  109,  110,
       70,  109,  110,   71,  109,  110,   67,  109,  110,   67,
      109,  110,   67,  109,  110,   67,  109,  110,   67,  109,

      110,   67,  109,  110,   67,  109,  110,   67,  109,  110,
       67,  109,  110,   67,  109,  110,   67,  109,  110,   67,
      109,  110,   67,  109,  110,   67,  109,  110,   67,  109,
      110,   72,  109,  110,  109,  110,   73,  109,  110,   14,
      110,   15,  110,   10,   14,  110,   14,  110,   14,  110,
       11,   14,  110,   14,  110,   14,  110,   14,  110,16393,
       31,  110,   32,  110,   31,  110,   13,  110,  110,  108,
       99,   66,   95,   83,   91,   96,   87,   97,   89,   75,
       29,   28,   93,   34,   33,   78,  104,  100,   98,   74,
      102,    2,   67,   67,   67,   49,   67,   67,   67,   67,

       67,   50,   67,   67,   67,   67,   67,   67,   67,   40,
       67,   67,   67,   84,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   82,   12,   18,   24,   26,   16,
       25,   23,   19,   20,   21,   22,   17, 8201,16393,16393,
       30,  106,16389,   66,   28,   35,   36,  105,   67,   85,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   47,
       67,   67,   52,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   56,   67,   67,   12,   26,   27, 8197,
    16389,   67,   67,   44,   67,   67,   67,   64,   67,   41,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,

       67,   67,   67,   54,   67,   37,   67,   67,   26,   27,
        1,16389,   39,   67,   45,   67,   53,   67,   67,   67,
       67,   38,   67,   67,   67,   67,   65,   67,   67,   67,
       67,   67,   67,   67,   51,   67,16390,   67,   42,   67,
       67,   67,   67,   61,   67,   67,   67,   57,   67,   63,
       67,   60,   67,   43,   67, 8198,   46,   67,   55,   67,
       48,   67,   67,   58,   67,   67,   62,   67,   67,   59,
       67
    } ;

static yyconst short int yy_accept[267] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    6,
        8,   10,   13,   15,   18,   21,   23,   26,   28,   31,
       34,   37,   40,   43,   46,   49,   52,   55,   58,   61,
       64,   67,   70,   73,   76,   78,   81,   84,   87,   90,
       93,   96,   99,  102,  105,  108,  111,  114,  117,  120,
      123,  126,  129,  132,  135,  137,  140,  142,  144,  147,
      149,  151,  154,  156,  158,  161,  163,  165,  167,  169,
      170,  170,  171,  172,  172,  173,  174,  175,  176,  177,
      178,  179,  180,  181,  182,  183,  184,  185,  185,  185,

      186,  187,  187,  188,  189,  190,  191,  192,  193,  194,
      195,  196,  198,  199,  200,  201,  202,  204,  205,  206,
      207,  208,  209,  210,  212,  213,  215,  216,  217,  218,
      219,  220,  221,  222,  223,  224,  225,  226,  227,  228,
      229,  230,  231,  232,  233,  234,  235,  236,  237,  237,
      238,  239,  240,  241,  242,  242,  243,  244,  244,  245,
      246,  247,  248,  248,  249,  251,  252,  253,  254,  255,
      256,  257,  258,  259,  260,  262,  263,  265,  266,  267,
      268,  269,  270,  271,  272,  273,  274,  276,  277,  278,
      279,  280,  280,  281,  281,  282,  283,  284,  286,  287,

      288,  290,  292,  293,  294,  295,  296,  297,  298,  299,
      300,  301,  302,  303,  304,  306,  308,  309,  310,  311,
      312,  312,  313,  315,  317,  319,  320,  321,  322,  324,
      325,  326,  327,  329,  330,  331,  332,  333,  334,  335,
      337,  338,  338,  339,  341,  342,  343,  344,  346,  347,
      348,  350,  352,  354,  356,  357,  359,  361,  363,  364,
      366,  367,  369,  370,  372,  372
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   28,   28,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   30,   29,   29,
       31,   32,   33,    1,   29,    1,   34,   35,   36,   37,

       38,   39,   29,   40,   41,   29,   42,   43,   29,   44,
       45,   46,   29,   47,   48,   49,   50,   51,   52,   53,
       54,   29,   55,   56,   57,    1,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    1,    6,    1,    1,    1,    1,    7,    8,    8,
        1,    1,    1,    7,    7,    7,    7,    7,    7,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    1,    1,    1
    } ;

static yyconst short int yy_base[286] =
    {   0,
        0,    1,   25,    0,   80,   84,   85,   88,   89,  119,
      403,   78,    2,    3,  402,  401,  403,  407,  407,  375,
      407,    5,    7,  376,    0,    0,  375,  391,  407,  407,
      407,  373,   80,  407,   81,  407,   86,  156,    0,  375,
      407,   75,   83,  371,  369,    0,  407,  407,   71,  347,
       70,   85,   88,   92,  354,  354,  344,   93,  352,   80,
       88,  355,  348,  407,  331,  407,  407,  407,  407,    0,
      205,  407,  168,  381,  111,  407,  407,  368,  407,  407,
      338,    9,  358,  377,    0,  407,  407,  407,  407,  407,
      407,  407,  407,  407,    0,  407,  126,    0,    4,  160,

      407,  357,  407,  407,  355,  407,  407,  407,    0,  342,
      331,    0,  339,  328,  341,  335,    0,  333,  324,  322,
      327,  322,  324,    0,  315,    0,  319,  142,  330,  315,
      329,  321,  320,  310,  312,  317,  407,    0,  407,  407,
      170,  407,  407,  407,  407,  407,  407,  407,    0,  407,
      407,  179,  352,  407,  310,  407,  345,  342,    0,    0,
        0,  120,  333,  407,    0,  304,  303,  296,  282,  293,
      274,  277,  273,  261,  265,  266,    0,  258,  141,  208,
      212,  203,  202,  201,  200,  209,    0,  203,    0,  175,
        0,  199,  407,    0,  239,  187,  198,    0,  191,  188,

        0,  195,  191,  196,  199,  183,  187,  181,  195,  190,
      186,  179,  181,  185,    0,    0,  182,  407,  407,  407,
      210,  215,    0,    0,    0,  174,  177,  178,    0,  178,
      172,  163,    0,  159,  171,  170,  161,  168,  163,    0,
      198,  190,  149,    0,  149,  156,  139,    0,  114,  101,
        0,    0,    0,    0,  407,    0,    0,    0,   92,    0,
       95,    0,   65,    0,  407,  258,  266,  274,  282,  284,
      286,  290,  292,  299,  305,  309,  317,  321,  324,  328,
      332,  336,  337,  344,  349
    } ;

static yyconst short int yy_def[286] =
    {   0,
      266,  266,  265,    3,  267,  267,  267,  267,  267,  267,
      267,   10,  268,  268,  269,  269,  265,  265,  265,  265,
      265,  265,  265,  265,  270,  271,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  272,  265,  265,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  265,  265,  265,  265,  265,  265,  273,
      265,  265,  265,   71,  274,  265,  265,  265,  265,  265,
      265,  265,  265,  275,  276,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  277,  265,  265,  278,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  265,  279,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  280,  265,
      265,  274,  265,  265,  265,  265,  265,  275,  276,  277,
      278,  265,  281,  265,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  279,  265,
      282,  265,  265,  283,  284,  272,  272,  272,  272,  272,

      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  265,  265,  265,
      285,  284,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      265,  285,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  265,  272,  272,  272,  272,  272,
      272,  272,  272,  272,    0,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265
    } ;

static yyconst short int yy_nxt[465] =
    {   0,
      265,  265,   19,   19,   77,   77,   82,   82,   82,   82,
       82,   82,  265,   78,   78,  265,  265,  100,  100,  100,
      100,  162,  162,   20,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   39,   39,   40,   41,   42,   43,
       44,   45,   46,   46,   46,   47,   21,   48,   49,   50,
       51,   52,   53,   54,   46,   55,   46,   46,   56,   57,
       58,   59,   60,   61,   46,   62,   63,   46,   46,   64,
       65,   66,   68,   67,   69,   70,   68,   68,   69,   70,
       68,   68,   89,   72,   70,   91,   72,   94,  102,  103,

      104,  264,   95,  114,   90,   92,   93,  105,  106,   67,
       96,   71,  115,  151,  110,   71,   73,  111,  112,   73,
       74,   68,  116,  118,   70,  121,  127,  133,  131,  117,
      119,  132,  263,  153,  134,  262,  122,  162,  162,  128,
      120,  123,  129,   97,   97,   97,   75,   75,   75,  261,
       74,  260,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   97,   97,   97,  150,  100,  100,  100,
      100,  151,  179,  259,  208,   98,  180,  190,  190,  190,
       99,  209,  218,  218,  218,  258,  257,  256,  241,  142,

      255,  153,  254,  253,  252,  251,  250,  249,   98,  139,
      140,  248,  247,  246,  245,  244,  243,  193,  241,  240,
      239,  238,  141,  141,  141,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  142,  226,  225,  224,
      223,  193,  143,  144,  220,  217,  216,  215,  145,  214,
      213,  146,  212,  147,  211,  148,  210,  149,   18,   18,
       18,   18,   18,   18,   18,   18,   67,   67,   67,   67,
       67,   67,   67,   67,   76,   76,   76,   76,   76,   76,
       76,   76,   79,   79,   79,   79,   79,   79,   79,   79,
       84,   84,   85,   85,  109,  207,  109,  109,  138,  138,

      152,  206,  205,  152,  152,  152,  152,  158,  204,  158,
      203,  158,  158,  159,  202,  159,  159,  160,  201,  160,
      160,  160,  160,  160,  160,  161,  200,  161,  189,  199,
      189,  189,  191,  198,  191,  195,  197,  196,  195,  195,
      219,  194,  219,  221,  221,  222,  157,  193,  222,  192,
      222,  222,  242,  242,  151,  242,  242,  188,  187,  186,
      185,  184,  183,  182,  181,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  157,  156,  155,  154,  265,  137,  136,  135,  130,
      126,  125,  124,  113,  108,  107,  101,   88,   87,   86,

       83,   81,  265,   80,   80,   68,   17,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265
    } ;

static yyconst short int yy_chk[465] =
    {   0,
        0,    0,    1,    2,   13,   14,   22,   22,   23,   23,
       82,   82,    0,   13,   14,    0,    0,   39,   39,   39,
       39,   99,   99,    1,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    5,   12,    5,    5,    6,    7,    6,    6,
        8,    9,   33,    7,    9,   35,    8,   37,   42,   42,

       42,  263,   37,   51,   33,   35,   35,   43,   43,   12,
       37,    5,   51,   75,   49,    6,    7,   49,   49,    8,
        9,   10,   52,   53,   10,   54,   58,   61,   60,   52,
       53,   60,  261,   75,   61,  259,   54,  162,  162,   58,
       53,   54,   58,   97,   97,   97,   10,   10,   10,  250,
       10,  249,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   38,   38,   38,   73,  100,  100,  100,
      100,  152,  128,  247,  179,   38,  128,  141,  141,  141,
       38,  179,  190,  190,  190,  246,  245,  243,  242,   73,

      241,  152,  239,  238,  237,  236,  235,  234,   38,   71,
       71,  232,  231,  230,  228,  227,  226,  222,  221,  217,
      214,  213,   71,   71,   71,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,   71,  200,  199,  197,
      196,  195,   71,   71,  192,  188,  186,  185,   71,  184,
      183,   71,  182,   71,  181,   71,  180,   71,  266,  266,
      266,  266,  266,  266,  266,  266,  267,  267,  267,  267,
      267,  267,  267,  267,  268,  268,  268,  268,  268,  268,
      268,  268,  269,  269,  269,  269,  269,  269,  269,  269,
      270,  270,  271,  271,  272,  178,  272,  272,  273,  273,

      274,  176,  175,  274,  274,  274,  274,  275,  174,  275,
      173,  275,  275,  276,  172,  276,  276,  277,  171,  277,
      277,  277,  277,  277,  277,  278,  170,  278,  279,  169,
      279,  279,  280,  168,  280,  281,  167,  166,  281,  281,
      282,  163,  282,  283,  283,  284,  158,  157,  284,  155,
      284,  284,  285,  285,  153,  285,  285,  136,  135,  134,
      133,  132,  131,  130,  129,  127,  125,  123,  122,  121,
      120,  119,  118,  116,  115,  114,  113,  111,  110,  105,
      102,   84,   83,   81,   78,   74,   65,   63,   62,   59,
       57,   56,   55,   50,   45,   44,   40,   32,   28,   27,

       24,   20,   17,   16,   15,   11,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "lexems.c"
#define INITIAL 0
#line 2 "lexems.c"
    #include <conio.h>
    #include <string.h>
	#include "parser.h"
	
	extern union YYSTYPE yylval;

	int start_condition[64];
	int condition_num = 0;
    char docName[64];
    char lexem[256];
	char html[512] = "";
	void beginCondition();
	void changeStartCondition(int condition);
	void addStartCondition(int condition);
	void returnStartCondition();
	void writeIntToUnion(char* num, char* base);
	void writeBinToUnion(char* num);
	void writeCharToUnion(char* const_char);
	void writeIdToUnion(char* id);
	void writeHtmlToUnion(char* uhtml);
	void printLex(char* lexemName, char* txt);
	void getDocName();
	int docNameCheck(char* name, char* txt);
	int strToNumber(char* num, char* base);
	int strToBin(char* num);
	void strcat_code(char* lex, int code);
	void strcat_strcode(char* lex, char* code);
#define YY_NEVER_INTERACTIVE 1
#define PHP 1

#define STR 2

#define STR_CONST 3

#define HEREDOC 4

#define NOWDOC 5

#define COMMENT 6

#define VAR_IN_STR 7

#line 673 "lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 52 "lexems.c"


#line 826 "lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yyleng;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 266 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 407 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 54 "lexems.c"
{if (strlen(html) != 0) {writeHtmlToUnion(html);} beginCondition(); addStartCondition(PHP); return HTML;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 55 "lexems.c"
{returnStartCondition();}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 57 "lexems.c"
strcat(html, yytext);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 58 "lexems.c"
strcat(html, yytext);
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 59 "lexems.c"
{if (strlen(html) != 0) {writeHtmlToUnion(html);} return HTML;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "lexems.c"
{getDocName(); strcpy(lexem, ""); addStartCondition(HEREDOC);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "lexems.c"
{getDocName(); strcpy(lexem, ""); addStartCondition(NOWDOC);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "lexems.c"
{strcpy(lexem, ""); addStartCondition(STR);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "lexems.c"
{strcpy(lexem, ""); addStartCondition(STR_CONST);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 66 "lexems.c"
{if (docNameCheck(docName, yytext)) {writeCharToUnion(lexem); returnStartCondition(); return CHAR_CONST;} else strcat(lexem, yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "lexems.c"
{writeCharToUnion(lexem); returnStartCondition(); return CHAR_CONST;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 "lexems.c"
{writeCharToUnion(lexem); returnStartCondition(); return CHAR_CONST;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 70 "lexems.c"
{writeCharToUnion(lexem); strcpy(lexem, yytext+1); unput('1'); addStartCondition(VAR_IN_STR); return CHAR_CONST;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 71 "lexems.c"
{writeIdToUnion(lexem); returnStartCondition(); return VARNAME_IN_STR;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 73 "lexems.c"
strcat(lexem, yytext);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 74 "lexems.c"
strcat(lexem, yytext);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 75 "lexems.c"
strcat(lexem, "\\");
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 76 "lexems.c"
strcat(lexem, "'");
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 77 "lexems.c"
strcat(lexem, "\"");
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 78 "lexems.c"
strcat(lexem, "\n");
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 79 "lexems.c"
strcat(lexem, "\r");
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 80 "lexems.c"
strcat(lexem, "\t");
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 81 "lexems.c"
strcat(lexem, "\v");
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 82 "lexems.c"
strcat(lexem, "\f");
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 83 "lexems.c"
strcat(lexem, "$");
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 84 "lexems.c"
strcat_code(lexem, 27);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 85 "lexems.c"
strcat_strcode(lexem, yytext);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 "lexems.c"
strcat_strcode(lexem, yytext);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 88 "lexems.c"

	YY_BREAK
case 29:
YY_RULE_SETUP
#line 90 "lexems.c"
{BEGIN(COMMENT);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 91 "lexems.c"
{BEGIN(PHP);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 92 "lexems.c"

	YY_BREAK
case 32:
YY_RULE_SETUP
#line 93 "lexems.c"

	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "lexems.c"
{writeIntToUnion(yytext, "%d"); return INT_CONST;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "lexems.c"
{writeIntToUnion(yytext, "%o"); return INT_CONST;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "lexems.c"
{writeIntToUnion(yytext, "%x"); return INT_CONST;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "lexems.c"
{writeBinToUnion(yytext); return INT_CONST;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 100 "lexems.c"
{yylval.intConstUnionType = 1; return BOOL_CONST;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 101 "lexems.c"
{yylval.intConstUnionType = 0; return BOOL_CONST;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 103 "lexems.c"
{return ARRAY;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 105 "lexems.c"
{return IF;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "lexems.c"
{return ELSE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 107 "lexems.c"
{return ELSEIF;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 108 "lexems.c"
{return SWITCH;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 109 "lexems.c"
{return CASE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 110 "lexems.c"
{return BREAK;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 111 "lexems.c"
{return DEFAULT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 113 "lexems.c"
{return FOR;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 114 "lexems.c"
{return FOREACH;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 115 "lexems.c"
{return AS;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 116 "lexems.c"
{return DO;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 117 "lexems.c"
{return WHILE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 119 "lexems.c"
{return NEW;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 120 "lexems.c"
{return CLASS;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 121 "lexems.c"
{return THIS;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 122 "lexems.c"
{return EXTENDS;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 123 "lexems.c"
{return PUBLIC;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 124 "lexems.c"
{return PUBLIC;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 125 "lexems.c"
{return PRIVATE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 126 "lexems.c"
{return PROTECTED;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "lexems.c"
{return STATIC;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "lexems.c"
{return PARENT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 130 "lexems.c"
{return FUNCTION;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 131 "lexems.c"
{return RETURN;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 133 "lexems.c"
{return ECHO;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 134 "lexems.c"
{return ECHO;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 136 "lexems.c"
{writeIdToUnion(yytext); return VARNAME;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 137 "lexems.c"
{writeIdToUnion(yytext); return ID;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 139 "lexems.c"
{return (unsigned char)'(';}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 140 "lexems.c"
{return (unsigned char)')';}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 141 "lexems.c"
{return (unsigned char)'[';}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 142 "lexems.c"
{return (unsigned char)']';}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 143 "lexems.c"
{return (unsigned char)'{';}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 144 "lexems.c"
{return (unsigned char)'}';}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 146 "lexems.c"
{return SETVALUE;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 147 "lexems.c"
{return ARROW;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 148 "lexems.c"
{return (unsigned char)'.';}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 149 "lexems.c"
{return (unsigned char)':';}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 150 "lexems.c"
{return SCOPEOP;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 152 "lexems.c"
{return (unsigned char)',';}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 153 "lexems.c"
{return (unsigned char)';';}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 155 "lexems.c"
{return (unsigned char)'!';}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 156 "lexems.c"
{return COR;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 157 "lexems.c"
{return CAND;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 158 "lexems.c"
{return POR;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 159 "lexems.c"
{return PAND;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 161 "lexems.c"
{return (unsigned char)'+';}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 162 "lexems.c"
{return PLUSAS;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 163 "lexems.c"
{return (unsigned char)'-';}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 164 "lexems.c"
{return MINUSAS;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 165 "lexems.c"
{return (unsigned char)'*';}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 166 "lexems.c"
{return MULTAS;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 167 "lexems.c"
{return (unsigned char)'/';}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 168 "lexems.c"
{return DIVAS;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 169 "lexems.c"
{return (unsigned char)'%';}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 170 "lexems.c"
{return MODAS;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 171 "lexems.c"
{return INC;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 172 "lexems.c"
{return DEC;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 174 "lexems.c"
{return EQ;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 175 "lexems.c"
{return NEQ;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 176 "lexems.c"
{return NEQ;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 177 "lexems.c"
{return (unsigned char)'>';}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 178 "lexems.c"
{return GEQ;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 179 "lexems.c"
{return (unsigned char)'<';}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 180 "lexems.c"
{return LEQ;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 181 "lexems.c"
{return TEQ;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 182 "lexems.c"
{return TNEQ;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 184 "lexems.c"
{return (unsigned char)'=';}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 186 "lexems.c"
;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 187 "lexems.c"
printf("character_not_found");
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 189 "lexems.c"
ECHO;
	YY_BREAK
#line 1501 "lexer.c"
			case YY_STATE_EOF(PHP):
			case YY_STATE_EOF(STR):
			case YY_STATE_EOF(STR_CONST):
			case YY_STATE_EOF(HEREDOC):
			case YY_STATE_EOF(NOWDOC):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(VAR_IN_STR):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 266 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 266 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 265);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 189 "lexems.c"


void beginCondition()
{
	start_condition[0] = INITIAL;
}

void addStartCondition(int condition)
{
	condition_num++;
	changeStartCondition(condition);
}

void changeStartCondition(int condition)
{
	start_condition[condition_num] = condition;
	BEGIN(condition);
}

void returnStartCondition()
{
	condition_num--;
	BEGIN(start_condition[condition_num]);
}

void writeIntToUnion(char* num, char* base)
{
	yylval.intConstUnionType = strToNumber(num, base);
}

void writeBinToUnion(char* num)
{
	yylval.intConstUnionType = strToBin(num);
}

void writeCharToUnion(char* const_char)
{
	yylval.charConstUnionType = (char*)malloc(sizeof(char)*256);
	strcpy(yylval.charConstUnionType, const_char);
}

void writeIdToUnion(char* id)
{
	yylval.idUnionType = (char*)malloc(sizeof(char)*100);
	strcpy(yylval.idUnionType, id);
}

void writeHtmlToUnion(char* uhtml)
{
	yylval.htmlUnionType = (char*)malloc(sizeof(char)*512);
	strcpy(yylval.htmlUnionType, uhtml);
	strcpy(uhtml, "");
}

void printLex(char* lexemName, char* txt)
{
	printf("%s found: [%s]\n", lexemName, txt);
}

void getDocName()
{
	if ((yytext[3] == '\"') || (yytext[3] == '\''))
	{
		strcpy(docName, yytext+4);
		docName[strlen(docName)-1] = 0;
	}
	else
		strcpy(docName, yytext+3);
}

int docNameCheck(char* name, char* txt)
{
	char dName[65];
	strcpy(dName, name);
	if(!strcmp(dName, txt) || !strcmp(strcat(dName, ";"), txt))
		return 1;
	else
		return 0;
}

int strToNumber(char* num, char* base)
{
	int number;
	sscanf(num, base, &number);
	return number;
}

int strToBin(char* num)
{
	int number = 0;
	int digit = 1;
	int i;
	for (i = strlen(num)-1; i > 1; i--)
	{
		number += (num[i]-48)*digit;
		digit *= 2;
	}
	return number;
}

void strcat_code(char* lex, int code)
{
	char h[2] = {(code%256), 0};
	strcat(lex, h);
}

void strcat_strcode(char* lex, char* code)
{
	int num;
	char copy[5];
	strcpy(copy, code);
	copy[0] = '0';
	if (copy[1] == 'x')
		sscanf(copy, "%x", &num);
	else
		sscanf(copy, "%o", &num);
	strcat_code(lex, num);
}